#!/bin/bash


echo -e "out:print:\e[H\e[2J"
echo -e "out:printl:\e[GThis is a beta version. Because of the bugs, YOUR POST may be LOST."
echo -e "out:printl:\e[GSAVE your posts LOCALLY!"
echo -e "out:printl:\e[GEnter your post's text here. Press Ctrl+Z to finish."

newline_seq="`echo -en "\nout:printl:\e[G\e[K"`"

cread()
{
	IFS= read -r c
	c="${c#user:key=}"
}

ctrl_key()
{
	read_ctrl_key
	case "$CTRL_KEY" in
		(Up)	curpos=0 ;;
		(Down)	curpos=len ;;
		(Left)	(((curpos--) || (curpos=0))) ;;
		(Right)	((curpos<len ? curpos++ : curpos)) ;;
		(Home)	curpos=0 ;;
		(End)	curpos=len ;;
		(Delete)	set_vars "" 1 ;;
	esac
}

set_vars()
{
	bspce=$1
	del=$2
	bs="${b:0:curpos-bspce}"
	be="${b:curpos+del}"
	b="${bs}${a}${be}"
	bc="${bs}${a}_${be}"
	sb="${bc//$'\r'/$newline_seq}"
	echo -e "out:print:\e[4H"
	echo "out:printc:$sb"
	echo "out:printc:"
}

b="`cat <$POST`"
b="${b//$'\n'/$'\r'}"
set_vars

while IFS= read -r a
do
	len=${#b}
	a="${a#user:key=}"
	if [ "_$a" = $'_\cz' ]
	then
		break
	elif [ "$a" = $'\x7f' ]
	then
		a=""
		set_vars 1
		(((curpos--)||(curpos=0)))
	elif [ "$a" = $'\e' ]
	then
		a=""
		ctrl_key
		set_vars
	else
		set_vars
		((curpos++))
	fi
done

b="${b//$'\r'/$'\n'}"
echo "$b" >$POST

