#!/bin/bash


echo "This is a beta version. Because the of bugs, YOUR POST may be LOST."
echo "SAVE your posts LOCALLY!"
echo "Enter your post's text here. Enter empty line to finish."

while IFS= read -r a
do
	[ -z "$a" ] && break;
	b="$b""$a"$'\n'
done
echo "$b" >$POST


exit



#!/bin/perl

$file=$ENV{POST};
$|++;

open P, ">$file";

print "This is a beta version. Because the of bugs, YOUR POST may be LOST.\n";
print "SAVE your posts LOCALLY!\n";
print "Enter your post's text here. Enter empty line to finish.\n";

while (<>) {
	/\S/ || last;
	$post .= $_;
}
if ($post) {
	print P  $post;
}

close P; 
