#!/bin/bash

# echo "out:printl:inside"
# echo "out:printl:$TARGET|$POST|$FILE|$PIC"

#pic_file=`perl -e 'use Time::HiRes; printf "%.06f.'"$FILE_EXT"'", Time::HiRes::time' |
#sed 's/\.//'`

maxlines=20
maxchars=1920
postlines=`wc -l <$POST`
postchars=`wc -c <$POST`

if [ -e "$POST" ]
then 
	if ((postlines>maxlines)) ||
	   ((postchars>maxchars))
	then
		echo out:print:`clear`
		echo "out:printl:POST TOO LONG"
		echo "out:printl:YOUR POST IS $postlines LINES, $postchars CHARS"
		echo "out:printl:MUST BE $maxlines LINES, $maxchars CHARS"

		while read c
		do
		[[ $c =~ ^user:key=.* ]] && exit 
		done
	fi
else
	echo >$POST
fi
	


if [ -d "$TARGET" ]
then
	postcount=$TARGET/post_count
	get=$(cat $postcount)
	echo $((++get)) >$postcount
	TARGET=$TARGET/$get
	echo no thread. $TARGET >&2
fi

perl -e '
	$file=q('"$FILE"');
	while (<STDIN>) {
		$post .= $_;
	}
	$post =~ s/\n/\\n/g;
	$post =~ s/@/<at>/g;
	$post =~ s/[\x00-\x1f]//g;
#	if (!$post) { $post="\n" }
	printf "%d001@%05d@%s@%s\n", 
	        time(), $ENV{XSID}, $post, $file;

' <$POST >>$TARGET
