#!/bin/bash

echo "out:printl:inside"

pic_file=`perl -e 'use Time::HiRes; printf "%.06f.crs", Time::HiRes::time' |
sed 's/\.//'`

maxlines=20
maxchars=1920
postlines=`wc -l <$POST`
postchars=`wc -c <$POST`

if [ -e "$POST" ]
then 
	if ((postlines>maxlines)) ||
	   ((postchars>maxchars))
	then
		echo out:print:`clear`
		echo "out:printl:POST TOO LONG"
		echo "out:printl:YOUR POST IS $postlines LINES, $postchars CHARS"
		echo "out:printl:MUST BE $maxlines LINES, $maxchars CHARS"

		while read c
		do
		[[ $c =~ ^user:key=.* ]] && exit 
		done
	fi
else
	echo >$POST
fi
	


if [ -z "$TARGET" ]
then
	postcount=board/$board/postcount
	get=$(cat $postcount)
	echo $((++get)) >$postcount
	TARGET=board/$board/$get
fi

perl -e '
	$pic_id=q('"$pic_file"');
	while (<STDIN>) {
		$post .= $_;
	}
	$post =~ s/\n/\\n/g;
	$post =~ s/@/<at>/g;
	$post =~ s/[\x00-\x1f]//g;
#	if (!$post) { $post="\n" }
	printf "%d001@%05d@%s@%s\n", 
	        time(), $ENV{XSID}, $post, $pic_id;

' <$POST >>$TARGET

cat $PIC >./pic/$pic_file &&
	rm $POST $PIC

