#!/bin/perl

$pwd=`dirname $0`;
chdir $pwd;

open SIN,  "<&$ENV{stdin}";
open SOUT, ">&$ENV{stdout}";

$attempts=3;

sub anagram
{
	@w=`cat data/words`;
	$_=$w[rand(@w)];
	my $r=$_;
	$b=int rand(length($_)-1);
	s/(.{$b})(.)(.)/$1$3$2/;
	chomp;
	return ($r, $_);
}

sub captcha
{
	print SOUT "To prove you're human, please solve the anagram: \n";
	my ($right, $wrong) = anagram;
	print SOUT $wrong . "\n";
	$_ = <STDIN>;
	s/^user:key=//;
#	$_ .= <SIN>;
	
	if ($r=/$right/) {
		print SOUT "Success. Hit Enter to continue... \n";
	} else {
		print SOUT "FAIL.\nreply: ${_}right: $right";
		print SOUT "Hit Enter to continue... \n";
	}
	$reply = <SIN>;
	return $r;
}

sub init
{
	#print "out:printl:".`reset`."\n";
	print "curses:cstop\n";
	print "out:printl:ang:" . anagram . "-\n";
	print "out:printl:ang:" . anagram . "-\n";
	print "out:printl:ang:" . anagram . "-\n";
	sleep 10;

	print "curses:cstart\n";
}
print "mod:use:curses\n";
print "curses:cstop\n";

#system("./consolemode");
$a=`stty icanon echo <&$ENV{stdin}`;
system("bash -c 'stty ecanon echo <$ENV{stdin}'");

for (my $i=0; $i<$attempts; $i++) {
	captcha &&
		exit 1;
}

exit 0
