#!/bin/bash

#lh=`echo -n $'\xe2\x96\x84'|iconv -f utf8`
lh=▄

(
sed -n 's/^curses:defspr:\([^:]\)*:\([^:]\)*://p' "$1" |
while read a && read b
do
	for ((i=0; i<${#b}; i++))
	do
		echo -en "\e[4${a:$i:1}m"
		echo -en "\e[3${b:$i:1}m"
		echo -en "$lh"
	done
	echo -en "\e[39m"
	echo -en "\e[49m"
	echo
done
#echo -en "\e[$((j))A"
#echo -en "\e[$((j?2:1))A"  no new line after pic
((j)) && echo -en "\e[A"
echo -en "\e[39m"
echo -en "\e[49m"
echo 
)|
sed 's/^/out:printl:/'
