#!/bin/bash
: <<\eof
About this file
===============

The install script for the server hasn't been tested yet, so, if you run into problems, please send an email.

How this works
==============

First, install a inetd/xinetd daemon which runs a telnet server.
Then, change the login program used by telnet to a script that always logs you in as the same user.
Next, change /etc/shadow to set that user's password as empty. That way you're logged in right away after you connect, no password asked.
The user you're logged in as has ~.profile that invokes a chroot environment, where the server is run.

Commands
========

eof

name=crazy_pipework

# Assure you're root
if [ $(id -u) != 0 ]
then 
	echo This program must be run as root.
	exit 1
fi

# 'Read username to run the server as (default="pipework")'
echo 'Enter the username to run the server as (default="pipework"):'
read user
user=${user-pipework}
dir=/home/$user
touch $dir/.hushlogin		# In case of SSH logins.
chrdir=/home/$user/chroot
cd "`dirname "$0"`"

echo Creating the user
useradd $user
chsh $user -s /bin/bash
mkdir $dir
#chown -R $user ~$user

echo pwd=$PWD
echo $dir
ls $dir/


echo Copying files
mkdir -p $chrdir/$name
cp -a ./* $chrdir/$name
cp script/* $dir
cp script/*.txt $dir

cp -r ./.git $chrdir/$name	# Copy Git repository

echo Seting password to empty string
# Search for this password cash to learn more about this trick 
sed -i "s/^\($user:\)[^:]*/"'\1$1$VNMbpxGH$sew7cnwH9ixU.x27UbFNn./' /etc/shadow

echo Editing ~.profile
cat <<\eof >>$dir/.profile
#!/bin/bash
export XSID=`cut -d ' ' -f4 /proc/$PPID/stat`
export CHROOTUID=`id -u`
export CHROOTGID=`id -g`

stty susp undef
sudo ./to_chroot.sh
exit
eof
chmod a+x $dir/.profile

echo Editing /etc/sudoers
cat <<eof >> /etc/sudoers
Defaults	env_keep+=XSID	# Generated by $name installer
Defaults	env_keep+=CHROOTUID
Defaults	env_keep+=CHROOTGID

$user ALL=NOPASSWD: /home/$user/to_chroot.sh
select\#* ALL=NOPASSWD: /home/$user/to_chroot.sh
$user ALL=NOPASSWD: /home/$user/mk_alias
eof

echo Creating a chroot environment. This may take a while...
cd $dir
./remake_chroot.sh
#FIXME: this is very slow

# Install telnetd
# apt-get install telnetd

echo Editing fstab
dev_dir=/home/$user/chroot/dev 
echo "/dev $dev_dir none defaults,bind 0 0" >> /etc/fstab
mount $dev_dir

echo Copying the screen program
chown -R $user $chrdir/chroot/home/.my-client
cp $name/bin/py_curses.py $chrdir/home/.my-client/bin/py_curses.py
cd $chrdir
chown -R $user home/
chown -R $user crazy_pipework/log/
chown -R $user crazy_pipework/pipe/
chown $user crazy_pipework/
chown $user crazy_pipework/curseserror 
# TODO (not tested):
chown -R $user crazy_pipework/cassettes/comment

cd - >/dev/null

echo if you run telnet through xinetd

cat <<\eof >/etc/xinetd.d/telnet 
service telnet
{
	disable  =  no
	socket_type  =  stream
	protocol = tcp
	port = 23 
	user = root
	group = root
	instances = UNLIMITED
	wait = no
	server = /usr/sbin/in.telnetd
	server_args = -L /usr/local/bin/my-autologin
}
eof

echo And make sure your /etc/xinetd.conf has the following lines:
cat <<\eof >>/dev/null
# Simple configuration file for xinetd
#
# Some defaults, and include /etc/xinetd.d/

defaults
{

# Please note that you need a log_type line to be able to use log_on_success
# and log_on_failure. The default is the following :
# log_type = SYSLOG daemon info
log_type = SYSLOG authpriv
log_type += FILE /var/log/xinetd
log_on_success = HOST PID DURATION USERID
log_on_failure = HOST ATTEMPT
cps = 10 30

}

includedir /etc/xinetd.d
eof

echo If you have inetd, add to /etc/inetd.conf:
# echo "telnet		stream	tcp	nowait	root /usr/sbin/tcpd	/usr/sbin/in.telnetd -L /usr/local/bin/my-autologin" >> /etc/inetd.conf

echo Creating a login program to automatically log in as pipework user
cat <<eof >/usr/local/bin/my-autologin 
#!/bin/sh
exec /bin/login -f $user
eof
chmod a+x /usr/local/bin/my-autologin 

# Re-read inetd config:

kill -HUP `pidof inetd`

# or

kill -HUP `pidof xinetd`

echo You may now delete the directory you installed from.
