#!/bin/bash

XSID=${XSID-$$}
HOME=${HOME-/home/`whoami`} # home is unset when run from xinetd
PIPEDIR="${pdir-"`dirname $0`/pipe/$XSID"}" # it can be set from server.bash
export ISPEED=120
#export COREPID=$$

#export -n pdir
export pdir="$PIPEDIR"
export BINDIR=./bin
export logdir=log/$XSID
export menu_fg=7 menu_bg=4
export XSID
declare -A pidbyid cmdbypid
mkdir $logdir

export new_core=1

cd `dirname $0`

if [ $IN_CHROOT ]
then
	export PATH=$PATH:/crazy_pipework/misc
else
	export PATH=$PATH:`pwd`/misc
fi

[ -d "$PIPEDIR" ] || mkdir "$PIPEDIR"

#for i in "$PIPEDIR/../"*; do ps -p ${i##*/} &>/dev/null || rm -r $i; done

to_loop=$PIPEDIR/to_loop
from_loop=$PIPEDIR/from_loop

cfg_ptrn="^main:set_config:"	# Now set in .pl. Export?


readconfig2="s/$cfg_ptrn//; \$conf=\$_; print \"evaling:\$conf\\n\"; eval \$conf;"


exec {stdout}>&1
exec {stdin}<&0

#trap 'tput sgr0; clear; echo killed; kill `ps|sed "1d;s/^ *//"|cut -f1 -d\ |grep -v $PPID`;' EXIT INT QUIT

#trap 'tput sgr0; clear; kill 0' EXIT INT QUIT
trap 'kill 0' EXIT INT QUIT

#trap 'tput sgr0; kill 0' EXIT INT QUIT

source "$BINDIR/include"

linebufferedcat()
{
	cat
	# while read a; do echo $a; done
	# grep --line-buffered ''
}

add_module() {
	local cmd_id="$1"
	local cmd="$2"

	mkpipe $cmd_id

	$cmd <$PIPEDIR/$cmd_id >$PIPEDIR/to_loop_$cmd_id 2>$logdir/$cmd_id &

	pidbyid[$cmd_id]=$!
	cmdbyid[$cmd_id]=$cmd

	# Is that needed anymore?
	for ((i=0; 1; i++))
	do
		[ -z "${pattern[i]}" ] && pattern[i]=$1 && break 
	done

	echo "main:add:$cmd_id"
}

init_cmds()
{
	if [ $new_core ]
	then
		add_module "mod" "$BINDIR/mod"
		add_module "user" "$BINDIR/user"
	else
	#	echo "main:add:mod"
	#	echo "main:add:user"
		echo "main:set_config:`mkptrn_pl`"
		echo "mod:set_io:$stdin:$stdout"
	fi
}

mkpipe()
{
	[ ! -p "$PIPEDIR/$1" ] && mkfifo "$PIPEDIR/$1" 
	[ ! -p "$PIPEDIR/to_loop_$1" ] && mkfifo "$PIPEDIR/to_loop_$1" 
}

mktask()
{
	local cmd_id="$1"
	local cmd="$2"

	mkpipe $cmd_id

	$cmd <$PIPEDIR/$cmd_id >$PIPEDIR/to_loop_$cmd_id 2>$logdir/$cmd_id &

	pidbyid[$cmd_id]=$!
	cmdbyid[$cmd_id]=$cmd

	for ((i=0; 1; i++))
	do
		[ -z "${pattern[i]}" ] && pattern[i]=$1 && break 
	done
}

mkptrn_pl()
{
	for (( i=0; i<${#pattern[@]}; i++ ))
	do
		echo -n 'open '"${pattern[i]}"', ">'"$PIPEDIR"'/'"${pattern[i]}"'"; '
		echo -n 'open in_'"${pattern[i]}"', "<'"$PIPEDIR"'/'"to_loop_${pattern[i]}"'"; '
		echo -n 'addfd \*in_'"${pattern[i]}"'; '
	done
	#echo -n 'while(<STDIN>){ '
	echo -n 'while (getln) { '
	#echo -n 'printf DEBUG "%0.3f $_", Time::HiRes::time-$^T; flush DEBUG; '
	echo -n 'llog; '
	for (( i=0; i<${#pattern[@]}; i++ ))
	do
		p="${pattern[i]}"
		echo -n "/^$p:/ && do { print $p; flush $p }; "
	done
	echo -n '/^main:get_config:/ && print ( (/^main:get_config:(.*)/), ":conf=$conf\n" ) ; '
#	echo -n "/^main:quit/ && do { on_exit; kill 'KILL', -getpgrp() }; "

	echo -n "/^main:set_config/ && last ; "
	echo -n '}; '
	echo -n "$readconfig2"
}

mkpipe "${to_loop##*/}"
mkpipe "${from_loop##*/}"

echo to_loop

echo logdir=$logdir
echo `pwd`

#perl -e 'use v5.10;
#use IO::Handle;
#use Time::HiRes;
#print "hi\n";' >/dev/null


linebufferedcat <$to_loop >$from_loop &

export stdin stdout

#{
if [ $new_core ]
then
	:
	#add_module "mod" "$BINDIR/mod"
	#add_module "user" "$BINDIR/user"
else
	mktask "mod" "$BINDIR/mod"
	mktask "user" "$BINDIR/user"
fi
#} >$to_loop


{ init_cmds; cat <$from_loop; } |  # tee log/bad1-$$ | # tee  >(cat >&$stdout) |
./core >&$to_loop

# perl -e "$init$poll$readconfig1$readconfig2" >&$to_loop

#wait ${pidbyid[mod]} 
echo wait
wait

rm -r "$PIPEDIR"

#echo main loop terminated
