#!/bin/bash

STATE=/tmp/state

print_log () {
	sed s/^/out:printc:/ < ../../$logdir/user;
}

read_key () {
	while read cmd
	do
		if [[ $cmd = user:key=q ]]
		then
			break 2
		elif [[ $cmd = user:key* ]]
		then
			break
		fi
	done
}

show_error () {
	echo out:print:`clear`error=$error;
	read_key
	print_log
	read_key
}

while true;
do
	./compile_sprites > ./level_1/sprites.crs
#	cd level_1
	TILE_SIZE=8 STATE=$STATE platform level_1
	error=$?
	rm level_1/sprites.crs
	case $error in
	0) rm $STATE; break ;;
	1) continue ;;
	*) show_error ;;
	esac
done
