#!/bin/bash

echo "mod:use:curses"
sleep 1
echo "curses:cstop"
sleep 1
stty icanon echo <&$stdin

#echo eval "$* <&$stdin >&$stdout" >>../misc/data/board
eval "$* <&$stdin >&$stdout"

stty -icanon -echo <&$stdin
echo "curses:cstart"
