#!/bin/perl

$thread=$1;
$post=$2;
$pic=$3;

open P, ">>../misc/data/board";

print "Enter post. Enter empty line to finish.\n";

while (<>) {
	/\S/ || last;
	$post .= $_;
}
$post =~ s/\n/\\n/g;
$post =~ s/@/<at>/g;
if ($post) {
	printf P "%d001@%05d@", time(), $ENV{XSID};
	print P  "$post\n";
}

close P; # msg, img
