#!/bin/bash

#lh=`echo -n $'\xe2\x96\x84'|iconv -f utf8`
lh=▄


w=`cut -d: -f1 <<<$1`
h=`cut -d: -f2 <<<$1`
d=`cut -d: -f3<<<$1`

(
for ((j=0; j<h; j+=2))
do
	for ((i=0; i<w; i++))
	do
		echo -en "\e[4${d:$((w*j+i)):1}m"
		echo -en "\e[3${d:$((w*j+i+w)):1}m"
		echo -en "$lh"
	done
	echo -en "\e[49m"
	echo
done
#echo -en "\e[$((j))A"
echo -en "\e[$((j?2:1))A"
echo -en "\e[39m"
echo -en "\e[49m"
echo 
)|
sed 's/^/out:printl:/'
