#!/bin/perl
#!/usr/bin/env perl
use Time::HiRes;

$INAME=game;
$inc=1;
$max=80;
$min=1;
$a=158;
$b=150;
$bgcolor=4;
$delay=.01;
$scrw=80;
$scrh=48;
#$scrh=24;
$sprw=16;
$sprh=16;
$tilew=16;
$tileh=16;
$testframes=1000; #00
$|++;
$nscr=0;
$psprw=$sprw;
$psprh=2*$sprh;
$origsprs=88;
$fps=20;
$updps=20;
$pdelay=1000000/$fps;
$repaint=0;
$sprmoved=0;
$walk=0;
$,=", ";
$vx=0;
$vy=0;
$inair=1;
$nklop=0;
$worldh=13*$tileh;

sub draw_world;


sub nscr
{
	my $x = $_[0];
	return int ($x/($scrw+$tilew));
}

sub onscr
{
	my $x = $_[0];
	my $w = $_[1];
	return int (($x+$w)/($scrw+$tilew));
}

sub nscry
{
	my $y = $_[0];
	return int ($y/($scrh));
}

sub onscry
{
	my $y = $_[0];
	my $h = $_[1];
	return int (($y+$h)/($scrh));
}

sub change_screen
{
	$onscr=$nscr;
	$onscry=$nscry;
	$nscr=nscr($a);
	$nscry=nscry($b);
	if ($nscr!=$onscr){
		draw_world;
		return 1
	}
	if ($nscry!=$onscry){
		draw_world;
		return 1
	}

	return 0
}

sub mkklop
{
	my %k;
	my $kx=$_[0];
	my $ky=$_[1];
	if ($state[$kx][$ky]) { return }
	$k{x}=$kx;
	$k{y}=$ky;
	$k{ox}=$_[0];
	$k{oy}=$_[1];
	$k{w}=16;
	$k{h}=16;
	$k{alive}=1;
	$k{visible}=1;
	$k{id}=scalar @klop;
	$k{move}+=@{$object{"klop"}{"move"}}[0];
	$state[$kx][$ky]=1;

	my $i=0;
	for $s (@{$object{"klop"}{"walk"}})
	{
		print "curses:newspr:klop$k{id}.walk.$i:" . $s . "\n";
		$i++;
	}

	return \%k;
}

sub showklop
{
	my $k=$_[0];
	$k->{visible}=1;
	print "curses:show:klop$k->{id}.walk.0\n";
	print "curses:show:klop$k->{id}.walk.1\n";
}

sub hideklop
{
	my $k=$_[0];
	$k->{visible}=0;
	print "curses:hide:klop$k->{id}.walk.0\n";
	print "curses:hide:klop$k->{id}.walk.1\n";
	print "curses:hide:klop$k->{id}.walk.0.+1\n";
	print "curses:hide:klop$k->{id}.walk.1.+1\n";
	print "curses:ref\n";
}

sub killklop
{
	my $k=$_[0];
	hideklop $k;
	$k->{alive}=0;
}

sub repaintklop
{
	my ($x, $y, $walk, $k) = @_;
	for (my $nwalk=0; $nwalk<@{$object{"klop"}{"walk"}}; $nwalk++) {
		if ($nwalk==$walk) {
			print "curses:show:klop$k->{id}.walk.$nwalk\n";
		} else {
			print "curses:hide:klop$k->{id}.walk.$nwalk\n";
			print "curses:hide:klop$k->{id}.walk.$nwalk.+1\n";
		}
	}
	$x-=$k->{w};
	print "curses:mvs2:klop$k->{id}.walk.$walk:$x:$y\n";
}

sub drawklop
{
	my $k=$_[0];
	my $hx=$k->{x}+$tilew*$nscr;

	if (onscr($hx, $k->{w})!=$nscr) {
		if ($k->{visible}) { hideklop $k }
		return;
	} else {
		if (!$k->{visible}) { showklop $k }
	}

	if (onscry($hy, $k->{w})!=$nscry) {
		if ($k->{visible}) { hideklop $k }
		return;
	} else {
		if (!$k->{visible}) { showklop $k }
	}

	my $nwalk=@{$object{"klop"}{"walk"}};
	my $walkn=$k->{x}%$nwalk;

	repaintklop( int($hx+$k->{w})%($scrw+$k->{w}),
	             int($k->{y})%($scrh+$k->{h}*2),
	             $walkn,
		     $k );

	$repaint++;
}

sub mkcharacter
{
	$a=$_[0];
	$b=$_[1];
	$charactervisible=1;
	$walkspeed=@{$object{character}{walkspeed}}[0];
	my $i=1;
	for $s (@{$object{"character"}{"walk"}})
	{
		print "curses:newspr:character.walk.$i:" . $s . "\n";
		print "curses:newspr:character.walk.$i.+1:" . $s . ".+1\n";
		$i++;
	}
}
sub hidecharacter
{
	my $i=1;
	$charactervisible=0;
	for $s (@{$object{"character"}{"walk"}})
	{
		print "curses:hide:character.walk.$i:" . $s . "\n";
		print "curses:hide:character.walk.$i.+1:" . $s . ".+1\n";
		$i++;
	}
}

sub killcharacter    #   ;_; 
{
	$b=0;
}

sub gettypes
{
	$k=$_[0];
	@k2=split(/\s+/, $types3{$k});	
	return @k2;
}

sub mkworld
{
	open TYPES, "</crazy_pipework/cassettes/platform/data/types.txt";
	@types2=<TYPES>;
	close TYPES;
	for (@types2)
	{
		if (/^\s*\/\//) { next }
		if (/^(.)\s*=\s*(.*)/) {
			$types3{$1}=$2;
		}
	}
	for $k (keys %types3) {
		@types4{$k}=[gettypes($k)]; #FIXME WHY???
	}
	open OBJ, "</crazy_pipework/cassettes/platform/data/objects.txt";
	@obj=<OBJ>;
	close OBJ;
	for (@obj)
	{
		if (/^\s*\/\//) { next }
		if (/^\s*(\S+)\.(\S+)\s*=\s*(.*)/) {
			@{$object{$1}{$2}}=split(/\s+/, $3);
		}
	}

	open CONFIG, "</crazy_pipework/cassettes/platform/data/config.txt";
	@conf1=<CONFIG>;
	close CONFIG;
	for (@conf1)
	{
		if (/^\s*\/\//) { next }
		if (/^\s*(\S+)\.(\S+)\s*=\s*(.*)/) {
			@{$conf{$1}{$2}}=split(/\s+/, $3);
		}
	}

	mkcharacter(150,158);
}

sub checksquares
{
	my $objx=$_[0];
	my $objy=$_[1];
	my $objw=$_[2];
	my $objh=$_[3];

}

sub chckptsqr
{
	my ($sx, $sy, $sex, $sey, $px, $py)=(@_);
	if ( ($px>$sx && $px<$sex) && ($py>$sy && $py<$sey) ) {
		return 1;
	}

	return 0;
}

sub sqrs_ist
{
	my ($sx, $sy, $ex, $ey, $sx2, $sy2, $ex2, $ey2)=(@_);
	if ( chckptsqr($sx, $sy, $ex, $ey, $sx2, $sy2) ||
	     chckptsqr($sx, $sy, $ex, $ey, $sx2, $ey2) ||
	     chckptsqr($sx, $sy, $ex, $ey, $ex2, $sy2) ||
	     chckptsqr($sx, $sy, $ex, $ey, $ex2, $ey2) ) {
		return 1;
	}
	else { return 0 }
}

sub can_move
{
	my $objx=$_[0];
	my $objy=$_[1];
	my $objw=$_[2];
	my $objh=$_[3];
	my $obj_is_klop=$_[4];
	my $leftsqr=int($objx/16);
	my $rightsqr=int(($objx+$objw-1)/16+1);
	my $topsqr=int($objy/16);
	my $botsqr=int(($objy+$objh-1)/16+1);
	($botsqr, $topsqr) = (12-$topsqr, 12-$botsqr);
	($botsqr, $topsqr) = ($topsqr, $botsqr);

	for (my $i=$leftsqr; $i<$rightsqr; $i++)
	{
		for (my $j=$botsqr; $j<=$topsqr; $j++)
		{
			my $sqr=$world[$i][$j];
			if ($sqr eq ""){ next }
			if ($sqr ~~ @obst){ return 0 }
			#if ($sqr ne "\""){ return 0 }
		}
	}

	if (!$obj_is_klop) {

		my $oex=$objx+$objw;
		my $oey=$objy+2*$objh;
		my $ox=$objx;
		my $oy=$objy;

		for my $k (@klop) {
			if (!$k->{alive}) { next }

			my $kx=$k->{x};
			my $ky=$k->{y};
			my $kex=$kx+$k->{w};
			my $key=$ky+$k->{h};

			if ( sqrs_ist($ox, $oy, $oex, $oey,
			              $kx, $ky, $kex, $key) ) {
				if ($inair) {
					killklop $k;
				} else {
					killcharacter;
				}
			}
		}
	}

	return 1;
}

sub repaint;

sub fall
{
	if (can_move($a-$sprw-16*$nscr, $b+1-$psprh, $sprw, $sprh-1)){
		$b++;
		$sprmoved++;
	}

}

sub updmove
{
	my $na, $nb;

	$vy-=1; 
	$rundec=@{$object{character}{walkstop}}[0];
	if (!$inair) {
		if ( $vx>$rundec ) { $vx-=$rundec }
		elsif ( abs($vx)>$rundec ) { $vx+=$rundec }
		else { $vx=0 }
	}

	$na= int $a+$vx;
	$nb= int $b-$vy;

	if ($vy) {
		if (can_move($a-$sprw-16*$nscr, $nb-$psprh, $sprw, $sprh-1)){
			$b=$nb;
			change_screen;
			$sprmoved++;
		}
		else {
			$vy=0;
			$inair=0;
		}
	}	

	if ($vx) {
		if (can_move($na-$sprw-16*$nscr, $b-$psprh, $sprw, $sprh-1)){
			$a=$na;
			$walk+=$vx>0?1:-1;
			change_screen;
			$sprmoved++;
		}	
	}	
	if ($a<$sprw) { $a=$sprw }
	if ($b>$worldh) { killcharacter }
	elsif ($b<0) { hidecharacter }
	else {
		if (!$charactervisible) { $charactervisible=1 }
	}
}

sub updklop
{
	my $k=$_[0];
	my $kx=$k->{x};
	my $ky=$k->{y};
	my $kh=$k->{h};
	my $kw=$k->{w};
	my $kw=$k->{w};

	if ($kx<-$kw) { killklop $k; return }
	if ($ky>$worldh) { killklop $k; return }

	my $nkx=$kx+$k->{move};
	my $nky=$ky+1;

	if (can_move($nkx, $ky+1-$kh, $sprw, $kh-1, 1)){
		$k->{x}=$nkx;
	} else { $k->{move} *= -1 }

	if (can_move($kx, $nky+1-$kh, $sprw, $kh-1, 1)){
		$k->{y}=$nky;
	}

	drawklop $k;	
}

sub update
{
	for my $k (@klop) {
		if ($k->{alive}) { updklop $k }
	}

	updmove;
	if ($sprmoved) {
		$sprmoved=0;
		$charactervisible && repaint;
		$repaint=1;
	}
	if ($repaint) {
		print "curses:ref\n";
		$repaint=0;
	}
	$SIG{ALRM}=\&update; Time::HiRes::ualarm($pdelay);
}

sub load_world
{
	open(F, "</crazy_pipework/cassettes/platform/data/w1-1.txt");
	while (<F>)
	{
		for (my $j=0; $j<15; $j++)
		{
			$world[$i][$j]=substr $_, $j, 1;
		}
		$i++;
	}
	close F;
}

sub draw_world
{
	for (my $i=int($scrw/16)*$nscr; $i*16<$scrw*($nscr+1); $i++)
	{
		for (my $j=int($scrh/16)*$nscry; $j*16<$scrh*($nscry+1); $j++)
		{
			my $sprtype=$world[$i][12-$j] ne "" ?
				$world[$i][12-$j] : 
				$world[0][0];
			my $rx=16*$i;
			my $sx=16*$i-$scrw*$nscr;
			my $sy=16*$j-$scrh*$nscry;
			$sy=int($sy/2);
			$k=$sprtype;
			for (@{$types4{$k}}) {
				if ($_ eq "obst") { push @obst, $k }
				if ($_ eq "klop") { push @klop, mkklop($rx, 2*$sy) }
				if ($_ eq "hide") { next }
			#	if (/show=(.+)/) { $sprtype=$1 } #FIXME 
				if (/show=(.*)/) { $sprtype=$1 || " " }
			}

			print "curses:paste:backdrop:spr$sprtype:0:0:$sx:$sy:16:8\n";
		}
	}
}

sub init_srv
{
	print "curses:lnmode:1\n";
	print "curses:progspr:load:$origsprs\n";
	print "curses:spr:walk1:$sprw:$sprh\n";
	print "curses:spr:walk2:$sprw:$sprh\n";
	print "curses:spr:walk3:$sprw:$sprh\n";
	print "curses:spr:walk1.+1:$sprw:$sprh\n";
	print "curses:spr:walk2.+1:$sprw:$sprh\n";
	print "curses:spr:walk3.+1:$sprw:$sprh\n";
#	print `bash -c 'cd \`dirname $0\`; cat data/*.crs'`;
}

sub sizeinit
{
	$inited=1;
	#sleep 2;
	#system("cat /crazy_pipework/cassettes/platform/data/logo.crs");
	
	my @logo=`cat /crazy_pipework/cassettes/platform/data/logo.crs`;
	for my $l (@logo) { print $l }
	$logo[0] =~ /spr:logo:([^:]+):([^:]+)/;
	my $lx=($scrw-$1)/2;
	my $ly=($scrh-int($2/2))/2;
	#my $ly=($scrh-$2)/2;
	print "curses:mvs2:logo:$lx:$ly\n";
	print "curses:ref\n";
	
	#system("cat /crazy_pipework/cassettes/platform/data/all2.crs");
	#system("cat /crazy_pipework/cassettes/platform/data/all_world_data.crs");
	my @logo=`cat /crazy_pipework/cassettes/platform/data/all2.crs`;
	for my $l (@logo) { print $l }
	my @logo=`cat /crazy_pipework/cassettes/platform/data/all_world_data.crs`;
	for my $l (@logo) { print $l }
	my @logo=`cat /crazy_pipework/cassettes/platform/data/klop-rev.crs`;
	for my $l (@logo) { print $l }

	#FIXME: backticks don't work in chroot
	mkworld;
	load_world;

	print "curses:hide:logo\n";
}

sub upd
{
	draws ($a%96-16, 1)
}

sub hideall
{
	print "curses:hide:character.walk.1\n";
	print "curses:hide:character.walk.2\n";
	print "curses:hide:character.walk.3\n";
	print "curses:hide:character.walk.1.+1\n";
	print "curses:hide:character.walk.2.+1\n";
	print "curses:hide:character.walk.3.+1\n";
}

sub hideall2
{
	print "curses:hide:walk1\n";
	print "curses:hide:walk2\n";
	print "curses:hide:walk3\n";
	print "curses:hide:walk1.+1\n";
	print "curses:hide:walk2.+1\n";
	print "curses:hide:walk3.+1\n";
}

sub draws
{
	hideall
	print "curses:show:character.walk." . ($walk/2%3+1) . "\n";
	print "curses:mvs2:character.walk." . ($walk/2%3+1) . ":$_[0]:$_[1]\n";
}

sub repaint
{
	#draws ($a%($scrw+$sprw)-$sprw, $b%($scrh+$sprh*2)-$sprh*2)
	draws ($a%($scrw+$sprw)-$sprw, $b%($scrh)-$sprh*2)
}

sub proc_cmd
{
	$_=$_[0];

	if (/^user:key=a/) {
		$vx=-$walkspeed;
	} elsif (/^user:key=d/) {
		$vx=$walkspeed;
	} elsif (/^user:key=w/) {
	} elsif (/^user:key=s/) {
	} elsif (/^user:key=A/) {
		$a--;
		$walk--;
		$sprmoved++;
	} elsif (/^user:key=D/) {
		$a++;
		$walk++;
		$sprmoved++;
	} elsif (/^user:key=W/) {
		$b--;
		$sprmoved++;
	} elsif (/^user:key=S/) {
		$b++;
		$sprmoved++;
	} elsif (/^user:key=r/) {
		draw_world;
		print "curses:ref\n";
	} elsif (/^user:key=-/) {
		$scrn--;
		if ($scrn<0){ $scrn=0 };
		draw_world 
	} elsif (/^user:key=\+/) {
		$scrn++;
		draw_world 
	} elsif (/^user:key=q/) {
		#print "curses:quit\n";
		exit
	} elsif (/^user:key=l/) {
		print "curses:stats\n";
	} elsif (/^user:key=t/) {
		print "curses:grpdel:screen$nscr\n";
	} elsif (/^user:key=T/) {
		print "curses:rmparts\n";
	} elsif (/^user:key=3/) {
		print "curses:spr:backdrop:" . 2*$scrw . ":" . 2*$scrh . "\n";
		$backdrop=1;
		draw_world;
		print "curses:ref\n";
	} elsif (/^user:key=4/) {
		print "curses:hide:backdrop\n";
		print "curses:ref\n";
	} elsif (/^user:key=5/) {
		print "curses:show:backdrop\n";
		print "curses:ref\n";
	} elsif (/^user:key=p/) {
		print "curses:pr:\033]4;1;#53186f\007\n";
	} elsif (/^user:key= /) {
		if (!$inair) {
			$vy=13;
			$inair++;
		}
	} elsif (/^user:key=b/) {
		$sshift--;
		print "curses:grpdel:screen$nscr\n";
		print "curses:ref\n";
	} elsif (/^user:key=n/) {
		$sshift++;
		print "curses:shft:backdrop:$sshift\n";
		print "curses:ref\n";
	} elsif (/^user:key=k/) {
		$kx=$okx;
	} elsif (/^user:screen:loaded/) {
		$SIG{ALRM}=\&update; Time::HiRes::ualarm($pdelay);
	} elsif (/^user:fall/) {
		if (can_move($a-$sprw, $b+1-$psprh, $sprw, $sprh-1)){
			$b++;
		}
		repaint;
		print "user:fall\n";
	} elsif (/^user:init/) {
		print "curses:pr:tst\n";
		sleep 1;
		init_srv
	} elsif (/^user:resize:([^:]*):([^:]*)/) {
		$scrw=$1;
		$scrh=$2;
		if (!$inited) { sizeinit }
		# FIXME: Should I delete the old one?
		print "curses:spr:backdrop:" . 2*$scrw . ":" . 2*$scrh . "\n";
		
#		update;
		change_screen or do { draw_world; }; #$sprmoved=1; repaint; };
		print "curses:ref\n";
	}
}

print "mod:use:out&&in&&net&&file&&curses\n"; 

while (<>) { proc_cmd $_ };
