#!/bin/bash
script_dir="`dirname "$0"`"
dir="$1"
ls -- "$1"/?.txt | 
while IFS= read -r i
do
	echo "$i"
	spr_fname="${i##*/}"
	spr_name="spr${spr_fname%.txt}"
	echo Sprite name="$spr_name"
	tr "`sed -n 1p "$dir/palette_transform.txt"`" \
	   "`sed -n 2p "$dir/palette_transform.txt"`" \
	   < "$i" |
		"$script_dir"/gen_sprite "$sprname" >"$dir/$spr_name".crs
done

